### ISSUE TITLE
[FIX] mock data 속성 추가

### ISSUE THREAD

**Issue by seowonn** [kb-skeleton/moneytracker#7]
## 🧐 설명!
- 카테고리 비율을 파악하기 위해 mock data 항목에 카테고리 항목 추가 필요
 

## ✔ 해야할 일! 
- 수행해야 하는 순서대로 특정 작업을 포함합니다. 
- [ ] mock data 재성성

**Comment by Eundongdong** [comment]
서원님 mock data에 "data"로 한번 묶어주셔야 데이터를 한번에 가져올 수 있는데, 다시 묶어주실 수 있을까요?
`[ "data":[{},{} ]`
